export const slides = [
  { name: 'basketDate',          date: '2024-09-18', title: 'Panier ou Vérité ?' },
  { name: 'blueDressJeMeurs1',   date: '2024-09-25', title: 'Dernier date mais pas le dernier' },
  { name: 'blueDressJeMeurs2',   date: '2024-09-30', title: 'Dernier date mais pas le dernier' },
  { name: 'blueDressJeMeurs4',   date: '2024-10-07', title: 'Dernier date mais pas le dernier' },
  { name: 'blueDressJeMeurs4',   date: '2024-10-07', title: 'Dernier date mais pas le dernier' },
  { name: 'blueDressJeMeurs3',   date: '2024-10-02', title: 'Dernier date mais pas le dernier' },
  { name: 'blueDressJeMeurs5',   date: '2024-10-12', title: 'Dernier date mais pas le dernier' },
  { name: 'btb1',                date: '2024-10-20', title: 'FirstDate' },
  { name: 'btb2',                date: '2024-10-23', title: 'FirstDate' },
  { name: 'btb3',                date: '2024-10-28', title: 'FirstDate' },
  { name: 'cafe1',               date: '2024-11-01', title: 'Coffee Work' },
  { name: 'clubMed',             date: '2024-11-08', title: 'Club Med' },
  { name: 'cook1',               date: '2024-11-15', title: 'Petit plats' },
  { name: 'fievre1',             date: '2024-11-22', title: 'Fièvre aka les photos qu\'on montrera a nos gosses' },
  { name: 'fievre2',             date: '2024-11-29', title: 'Fièvre aka les photos qu\'on montrera a nos gosses' },
  { name: 'fievre3',             date: '2024-12-03', title: 'Fièvre aka les photos qu\'on montrera a nos gosses' },
  { name: 'ghibliBasket',        date: '2024-12-10', title: 'Meme l\'ordi trouve qu\'on est cute', ext: 'PNG' },
  { name: 'ghibliPhotoMaton',    date: '2024-12-17', title: 'Meme l\'ordi trouve qu\'on est cute', ext: 'PNG' },
  { name: 'melon',               date: '2024-12-23', title: 'Essai Photo n1' },
  { name: 'paparazzi1',          date: '2025-01-05', title: 'Paparazzi !!' },
  { name: 'paparazzi2',          date: '2025-01-06', title: 'Paparazzi !!' },
  { name: 'photobooth',          date: '2025-01-15', title: 'Mamacita' },
  { name: 'picnic1',             date: '2025-01-22', title: 'Second Date' },
  { name: 'picnic2',             date: '2025-01-29', title: 'Second Date' },
  { name: 'picnic3',             date: '2025-02-04', title: 'Second Date' },
  { name: 'picnic4',             date: '2025-02-11', title: 'Second Date' },
  { name: 'pizza1',              date: '2025-02-18', title: 'Nos 1 mois' },
  { name: 'pizza2',              date: '2025-02-25', title: 'Nos 1 mois' },
  { name: 'quai2',               date: '2025-03-03', title: 'Essai Photo n2' },
  { name: 'sofa',                date: '2025-04-07', title: 'Mon pull, mon odeur' }
].map((s) => ({
  url: `/${s.name}.${s.ext ?? 'webp'}`,
  date: s.date,
  title: s.title,
}));